# Generated by Django 3.2.12 on 2024-04-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20191122_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcategory',
            old_name='category_name',
            new_name='nom_de_la_salle',
        ),
    ]
