# Generated by Django 3.2.12 on 2024-04-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_category_name_roomcategory_nom_de_la_salle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcategory',
            old_name='summary',
            new_name='description',
        ),
    ]
