# Generated by Django 3.2.12 on 2024-04-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_rename_summary_roomcategory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcategory',
            old_name='total_rooms',
            new_name='nombre_de_personnes',
        ),
    ]
