# Generated by Django 3.2.12 on 2024-04-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20240416_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='motif_de_reservation',
            field=models.CharField(default='', max_length=150),
        ),
    ]
