# Generated by Django 3.2.12 on 2024-04-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20240416_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcategory',
            old_name='nombre_de_personnes',
            new_name='maxCapacity',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='image_de_la_salle',
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='motif_de_reservation',
            field=models.CharField(default='', max_length=150),
        ),
    ]
