# Generated by Django 3.2.12 on 2024-04-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20240418_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcategory',
            old_name='nom_de_la_salle',
            new_name='libRoom',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='motif_de_reservation',
        ),
    ]
