# Generated by Django 3.2.12 on 2024-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20240418_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='description',
            field=models.TextField(default='Entrez la description'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='image',
            field=models.ImageField(default='upload/default.jpg', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='maxCapacity',
            field=models.IntegerField(default='1'),
        ),
    ]
