# Generated by Django 3.2.12 on 2024-04-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roomcategory_motif_de_reservation'),
        ('rooms', '0009_auto_20240418_1523'),
    ]

    operations = [
    ]
