# Generated by Django 3.2.12 on 2024-04-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_merge_20240423_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='motif_de_reservation',
        ),
    ]
