# Generated by Django 3.2.12 on 2024-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_roomcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='image',
            field=models.ImageField(default='/default_room_image/default.jpg', upload_to='default_room_image'),
        ),
    ]
