# Generated by Django 3.2.12 on 2024-05-02 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('groups', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'en attente'), ('canceled', 'annulé'), ('validated', 'validé')], max_length=100)),
                ('motif', models.CharField(max_length=100)),
                ('peopleAmount', models.IntegerField(default=1)),
                ('equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
