# Generated by Django 3.2.12 on 2024-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedequipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedequipment',
            name='peopleAmount',
        ),
        migrations.AlterField(
            model_name='bookedequipment',
            name='status',
            field=models.CharField(choices=[('loaned', 'prêté'), ('canceled', 'annulé'), ('back', 'rendu'), ('late', 'en retard')], default='loaned', max_length=100),
        ),
    ]
