# Generated by Django 3.2.12 on 2024-05-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedequipments', '0002_auto_20240530_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedequipment',
            name='status',
            field=models.CharField(choices=[('pending', 'en attente'), ('loaned', 'prêté'), ('canceled', 'annulé'), ('back', 'rendu'), ('late', 'en retard')], default='pending', max_length=100),
        ),
    ]
