# Generated by Django 3.2.12 on 2024-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedequipments', '0003_alter_bookedequipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedequipment',
            name='groups',
            field=models.CharField(choices=[(None, 'Sélectionnez un laboratoire'), ('CReSTIC', 'CReSTIC'), ('Lab-i*', 'Lab-i*'), ('LICIIS', 'LICIIS'), ('Autre', 'Autre')], max_length=100),
        ),
    ]
