# Generated by Django 3.2.12 on 2024-06-14 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookedequipments', '0004_alter_bookedequipment_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedequipment',
            name='last_date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière date de modification'),
        ),
        migrations.AddField(
            model_name='bookedequipment',
            name='last_person_modified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_equipement', to=settings.AUTH_USER_MODEL, verbose_name='Dernière personne ayant modifié'),
        ),
    ]
