# Generated by Django 3.2.12 on 2024-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentcategory',
            old_name='libRoom',
            new_name='libEquipment',
        ),
        migrations.RemoveField(
            model_name='equipmentcategory',
            name='maxCapacity',
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='description',
            field=models.TextField(default='Entrez la description'),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='image',
            field=models.ImageField(default='default_image/default.jpg', upload_to='default_image'),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='nbrEquipments',
            field=models.IntegerField(default='1'),
        ),
    ]
