# Generated by Django 3.2.12 on 2024-05-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20240530_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='image',
            field=models.ImageField(default='/default_equipment_image/default.jpg', upload_to='default-equipment_image'),
        ),
    ]
