# Generated by Django 3.2.12 on 2024-04-19 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookedrooms', '0002_bookedroom_nbr_of_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedroom',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='bookedroom',
            name='start_date',
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='groups',
            field=models.CharField(default='aucun', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='startTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='status',
            field=models.CharField(default='en cours', max_length=100),
            preserve_default=False,
        ),
    ]
