# Generated by Django 3.2.12 on 2024-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedrooms', '0003_auto_20240419_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='status',
            field=models.CharField(choices=[('pending', 'en attente'), ('canceled', 'annulé'), ('validated', 'validé')], max_length=100),
        ),
    ]
