# Generated by Django 3.2.12 on 2024-04-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedrooms', '0005_bookedroom_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='motif',
            field=models.CharField(max_length=100),
        ),
    ]
