# Generated by Django 3.2.12 on 2024-04-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookedrooms', '0006_alter_bookedroom_motif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedroom',
            old_name='nbr_of_rooms',
            new_name='peopleAmount',
        ),
    ]
