# Generated by Django 3.2.12 on 2024-05-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedrooms', '0007_rename_nbr_of_rooms_bookedroom_peopleamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='groups',
            field=models.CharField(choices=[('CReSTIC', 'CReSTIC'), ('Labi*', 'Labi*'), ('Liciis', 'Liciis')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bookedroom',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('canceled', 'Annulé'), ('validated', 'Validé')], max_length=100),
        ),
    ]
