# Generated by Django 3.2.12 on 2024-05-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookedrooms', '0011_alter_bookedroom_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='groups',
            field=models.CharField(choices=[(None, 'Sélectionnez un laboratoire'), ('CReSTIC', 'CReSTIC'), ('Lab-i*', 'Lab-i*'), ('LICIIS', 'LICIIS'), ('Autre', 'Autre')], max_length=100),
        ),
    ]
