# Generated by Django 3.2.12 on 2024-05-30 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookedrooms', '0012_alter_bookedroom_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='last_date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière date de modification'),
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='last_person_modified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to=settings.AUTH_USER_MODEL, verbose_name='Dernière personne ayant modifié'),
        ),
    ]
